name: First Workflow
on: [push]

jobs:
  run-shell:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Multiline Command
        run: |
          node -v
          npm -v
